name: elevar_fitness_tracker
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.40.0

  sqflite: ^2.3.0

  path: any

  cupertino_icons: ^1.0.2

  loading_animation_widget: ^1.2.0+4

  firebase_core: ^2.21.0

  cloud_firestore: ^4.12.2

  http: ^1.1.0

  flutter_typeahead: ^4.8.0

  pedometer: ^4.0.1

  flutter_local_notifications: ^16.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  firebase_storage: ^11.5.4
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  timezone: ^0.9.2


flutter:
  uses-material-design: true
  fonts:
    - family: Geologica
      fonts:
        - asset: fonts/Geologica_Auto-Thin.ttf
          weight: 100
        - asset: fonts/Geologica_Auto-ExtraLight.ttf
          weight: 200
        - asset: fonts/Geologica_Auto-Light.ttf
          weight: 300
        - asset: fonts/Geologica_Auto-Regular.ttf
          weight: 400
        - asset: fonts/Geologica_Auto-Medium.ttf
          weight: 500
        - asset: fonts/Geologica_Auto-Semibold.ttf
          weight: 600
        - asset: fonts/Geologica_Auto-Bold.ttf
          weight: 700
        - asset: fonts/Geologica_Auto-ExtraBold.ttf
          weight: 800
        - asset: fonts/Geologica_Auto-Black.ttf
          weight: 900